build: upd deps

diff --git a/.docker/php/Dockerfile b/.docker/php/Dockerfile
--- a/.docker/php/Dockerfile
+++ b/.docker/php/Dockerfile
@@ -1,10 +1,32 @@
-# alpine3.13 is broken
-FROM php:7.4-fpm-alpine3.12
+FROM php:7.4-fpm-alpine3.13
 
+# Update repo and install some utilites
 RUN set -xe \
     && apk update \
     && apk upgrade \
+    && apk --no-cache add htop unzip gzip
+
+# Composer
+RUN set -xe \
+    && curl -L -o /composer.phar https://github.com/composer/composer/releases/download/2.0.11/composer.phar \
+    && chmod 755 /composer.phar
+
+# Blackfire https://blackfire.io/docs/php/integrations/php-docker
+RUN set -xe \
+    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/alpine/amd64/$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
+    && mkdir -p /tmp/blackfire \
+    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
+    && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so \
+    && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz
+
+# PHP
+RUN set -xe \
     && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
+
+    # Xdebug, APCU
+    && pecl install apcu \
+    && pecl install xdebug \
+    && docker-php-ext-enable apcu xdebug \
 
     # Sodium
     && apk add --no-cache libsodium-dev \
@@ -16,42 +38,17 @@ RUN set -xe \
     && docker-php-ext-install intl \
     && docker-php-ext-enable intl \
 
-    # Xdebug
-    && pecl install xdebug \
-    && docker-php-ext-enable xdebug \
-
     # Postgresql
     && apk add --no-cache postgresql-dev \
     && docker-php-ext-install pdo_pgsql \
-    && docker-php-ext-enable pdo_pgsql \
+    && docker-php-ext-enable pdo_pgsql
 
-    # APCU
-    && pecl install apcu \
-    && docker-php-ext-enable apcu \
-
-    # Blackfire https://blackfire.io/docs/integrations/docker/index
-    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/alpine/amd64/$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
-    && mkdir -p /tmp/blackfire \
-    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire \
-    && mv /tmp/blackfire/blackfire-*.so $(php -r "echo ini_get ('extension_dir');")/blackfire.so \
-    && rm -rf /tmp/blackfire /tmp/blackfire-probe.tar.gz \
-
-    # Cleanup
+# Cleanup
+RUN set -xe \
     && apk del --no-cache .build-deps \
     && apk del --no-cache icu-dev \
     && apk del --no-cache libsodium-dev \
     && rm -rf /tmp/* /var/cache/apk/*
-
-
-# Composer
-RUN set -xe \
-    && curl -L -o /composer.phar https://github.com/composer/composer/releases/download/2.0.11/composer.phar \
-    && chmod 755 /composer.phar
-
-
-# utilites
-RUN set -xe \
-    && apk --no-cache add htop unzip
 
 
 WORKDIR /var/www/app
